### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by visch** [AutoIDM/tap-googleads#4]
- [x]  CI
- [x]  POC (0.0.1)
- [x]  POC (0.1.1) - 5 more streams
- [x]  1.0.0 Release - All Streams, with Discovery and everything
- [x]  Rate Limiting
- [x]  Error Handling
- [x]  Testing with actual data
- [ ]  Be sure documentation is clear (Should happen along the way)
- [ ]  Add MIT License
- [ ]  Release 1.0.0 to PyPi
- [ ]  Submit to Meltano Hub
